apiVersion: v1
kind: Service
metadata:
  name: service-login
  namespace: urbanfood
  labels:
    app: app-login
spec:
  ports:
  - name: service-login-http
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: app-login
  type: LoadBalancer